<!DOCTYPE HTML><%@page language="java"
	contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
	
<%@ taglib prefix="c" uri="http://www.springframework.org/tags" %>

<html>
<head>
<title>index</title>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
</head>
<body>
	
	
	
	<h1>Soy yo</h1>
	
	
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="#">Spring MVC Web Gallery</a>

            <div class="nav-collapse collapse">

                <sec:authorize access="isAnonymous()">
                <ul class="nav"> <!-- TODO autogenerated li class="active" -->
                    <li><a href="">Home</a></li>
                    <li><a href="#signin" role="button" data-toggle="modal">Sign In</a></li>
                    <li><a href="#register" role="button" data-toggle="modal">Register</a></li>
                </ul>
                </sec:authorize>


            </div>

        </div>
    </div>
</div>
	
</body>
</html>


